package com.fiscal.pfa.models;
// Generated May 26, 2020, 2:45:30 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parametre generated by hbm2java
 */
@Entity
@Table(name = "parametre", catalog = "fiscal")
public class Parametre implements java.io.Serializable {

	private int idParam;
	private String nomParam;
	private BigDecimal valeure;

	public Parametre() {
	}

	public Parametre(int idParam) {
		this.idParam = idParam;
		
	}

	public Parametre(int idParam, String nomParam, BigDecimal valeure) {
		this.idParam = idParam;
		this.nomParam = nomParam;
		this.valeure = valeure;

	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idParam", unique = true, nullable = false)
	public int getIdParam() {
		return this.idParam;
	}

	public void setIdParam(int idParam) {
		this.idParam = idParam;
	}

	@Column(name = "nomParam", length = 200)
	public String getNomParam() {
		return this.nomParam;
	}

	public void setNomParam(String nomParam) {
		this.nomParam = nomParam;
	}

	@Column(name = "valeure", precision = 10, scale = 5)
	public BigDecimal getValeure() {
		return this.valeure;
	}

	public void setValeure(BigDecimal valeure) {
		this.valeure = valeure;
	}



}
