package com.fiscal.pfa.models;
// Generated May 26, 2020, 2:45:30 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name = "societe", catalog = "fiscal")
public class Societe implements java.io.Serializable {

	private Long idSociete;
	private String nomSociete;
	private String categorie;
	private String taille;
	private String statutJuridique;
	private String nationalite;
	private String secteur;
	private String siegeSocial;
	
	private Set<Archive> archives = new HashSet(0);

	public Societe() {
	}

	public Societe(Long idSociete) {
		this.idSociete = idSociete;
		
	}

	public Societe(Long idSociete, String nomSociete, String categorie, String taille, String statutJuridique,
			String nationalite, String secteur, String siegeSocial, Set<Archive> archives) {
		this.idSociete = idSociete;
		this.nomSociete = nomSociete;
		this.categorie = categorie;
		this.taille = taille;
		this.statutJuridique = statutJuridique;
		this.nationalite = nationalite;
		this.secteur = secteur;
		this.siegeSocial = siegeSocial;

		this.archives = archives;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idSociete", unique = true, nullable = false)
	public Long getIdSociete() {
		return this.idSociete;
	}

	public void setIdSociete(Long idSociete) {
		this.idSociete = idSociete;
	}

	@Column(name = "nomSociete", length = 200)
	public String getNomSociete() {
		return this.nomSociete;
	}

	public void setNomSociete(String nomSociete) {
		this.nomSociete = nomSociete;
	}

	@Column(name = "categorie", length = 200)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "taille", length = 200)
	public String getTaille() {
		return this.taille;
	}

	public void setTaille(String taille) {
		this.taille = taille;
	}

	@Column(name = "statutJuridique", length = 200)
	public String getStatutJuridique() {
		return this.statutJuridique;
	}

	public void setStatutJuridique(String statutJuridique) {
		this.statutJuridique = statutJuridique;
	}

	@Column(name = "nationalite", length = 200)
	public String getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(String nationalite) {
		this.nationalite = nationalite;
	}

	@Column(name = "secteur", length = 200)
	public String getSecteur() {
		return this.secteur;
	}

	public void setSecteur(String secteur) {
		this.secteur = secteur;
	}

	@Column(name = "siegeSocial", length = 500)
	public String getSiegeSocial() {
		return this.siegeSocial;
	}

	public void setSiegeSocial(String siegeSocial) {
		this.siegeSocial = siegeSocial;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societe")
	public Set<Archive> getArchives() {
		return this.archives;
	}

	public void setArchives(Set<Archive> archives) {
		this.archives = archives;
	}

}