package com.fiscal.pfa.models;
// Generated May 26, 2020, 2:45:30 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeFichier generated by hbm2java
 */
@Entity
@Table(name = "type_fichier", catalog = "fiscal")
public class TypeFichier implements java.io.Serializable {

	private int idType;
	private String nomType;
	private Parametre parametre;
	private Set<Archive> archives = new HashSet(0);

	public TypeFichier() {
	}

	public TypeFichier(int idType) {
		this.idType = idType;
		
	}

	public TypeFichier(int idType, String nomType, Set<Archive> archives, Parametre parametre) {
		this.idType = idType;
		this.nomType = nomType;
		this.parametre = parametre;
		this.archives = archives;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idType", unique = true, nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "nomType", length = 200)
	public String getNomType() {
		return this.nomType;
	}

	public void setNomType(String nomType) {
		this.nomType = nomType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	public Parametre getParametre() {
		return this.parametre;
	}

	public void setParametre(Parametre parametre) {
		this.parametre = parametre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeFichier")
	public Set<Archive> getArchives() {
		return this.archives;
	}

	public void setArchives(Set<Archive> archives) {
		this.archives = archives;
	}

}
